org: hisa1229
service: daily-report
frameworkVersion: '2'
variablesResolutionMode: 20210326
custom:
  env: ${file(./.env.yml)}
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  stage: dev
  region: ap-northeast-1
  environment:
    SLACK_BOT_TOKEN: ${self:custom.env.SLACK_BOT_TOKEN}
    SLACK_SIGNING_SECRET: ${self:custom.env.SLACK_SIGNING_SECRET}
    REDMINE_URL: ${self:custom.env.REDMINE_URL}
functions:
  redmine-api:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
